### ISSUE TITLE
Umbrella 2.0

### ISSUE THREAD

**Issue by robinweser** [robinweser/react-layout-components#15]
This major release will ship a whole new set of Components
- [x] Box (Flexbox)
- [x] Container (Padding, Margin, Border)
- [x] ScrollView
- [x] Page

Shortcut Components
- [x] VBox (Vertical flexbox)
- [x] Center (Totally center children)
- [x] Flex (flex: 1 0 auto)
